ls

diff --git a/.github/workflows/linter.yml b/.github/workflows/linter.yml
--- a/.github/workflows/linter.yml
+++ b/.github/workflows/linter.yml
@@ -11,15 +11,16 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Run docker Image
-        env:
-          build_image: clelange/cc7-cmssw-cvmfs:latest
-          docker_options: --cap-add SYS_ADMIN --cap-add=MKNOD --security-opt apparmor=unconfined -e CVMFS_MOUNTS="cms.cern.ch" --device /dev/fuse -i
-        run: |
-            docker run ${{ env.docker_options }} ${{ env.build_image }} /bin/bash \
-            -c 'source /cvmfs/cms.cern.ch/cmsset_default.sh && echo Succeeded to source || exit_on_error "Failed to source"!; \
-             scramv1 project CMSSW ${{ env.cmssw_ver }}; cd ${{ env.cmssw_ver }}/src ; "eval `scramv1 runtime -sh`" ; \
-             echo ${{ env.cmssw_ver }}/src/machineLearning/machineLearning; git clone ${{ env.repo_url}} ${{ env.cmssw_ver }}/machineLearning/machineLearning;\
-             cd machineLearning/machineLearning; sudo python -m pip install pycodestyle; pycodestyle . '
+        run: ls
+        # env:
+        #   build_image: clelange/cc7-cmssw-cvmfs:latest
+        #   docker_options: --cap-add SYS_ADMIN --cap-add=MKNOD --security-opt apparmor=unconfined -e CVMFS_MOUNTS="cms.cern.ch" --device /dev/fuse -i
+        # run: |
+        #     docker run ${{ env.docker_options }} ${{ env.build_image }} /bin/bash \
+        #     -c 'source /cvmfs/cms.cern.ch/cmsset_default.sh && echo Succeeded to source || exit_on_error "Failed to source"!; \
+        #      scramv1 project CMSSW ${{ env.cmssw_ver }}; cd ${{ env.cmssw_ver }}/src ; "eval `scramv1 runtime -sh`" ; \
+        #      echo ${{ env.cmssw_ver }}/src/machineLearning/machineLearning; git clone ${{ env.repo_url}} machineLearning/machineLearning;\
+        #      cd machineLearning/machineLearning; sudo python -m pip install pycodestyle; pycodestyle . '
         # Can't use the alias cmsrel, would need to echo it to .bashrc. Though this is the only place we need that alias.
 
 # /commit/${{ github.sha }}
