alias

diff --git a/.github/workflows/linter.yml b/.github/workflows/linter.yml
--- a/.github/workflows/linter.yml
+++ b/.github/workflows/linter.yml
@@ -4,20 +4,23 @@ on: [push]
 
 env:
   cmssw_ver: CMSSW_10_2_10
+  repo_url: 
 
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - name: Run docker Image
-        env:
-          build_image: clelange/cc7-cmssw-cvmfs:latest
-          docker_options: --cap-add SYS_ADMIN --cap-add=MKNOD --security-opt apparmor=unconfined -e CVMFS_MOUNTS="cms.cern.ch" --device /dev/fuse -i
-        run: |
-            docker run ${{ env.docker_options }} ${{ env.build_image }} /bin/bash \
-            -c 'source /cvmfs/cms.cern.ch/cmsset_default.sh && echo Succeeded to source || exit_on_error "Failed to source"!; \
-             scramv1 project CMSSW ${{ env.cmssw_ver }}; ls ; cd ${{ env.cmssw_ver }} ; pwd '
-        # Can't use the alias cmsrel, would need to echo it to .bashrc. Though this is the only place we need that alias.
+      run: echo ${{ github.repository }}
+      run: echo ${{ github.token }}
+      # - name: Run docker Image
+      #   env:
+      #     build_image: clelange/cc7-cmssw-cvmfs:latest
+      #     docker_options: --cap-add SYS_ADMIN --cap-add=MKNOD --security-opt apparmor=unconfined -e CVMFS_MOUNTS="cms.cern.ch" --device /dev/fuse -i
+      #   run: |
+      #       docker run ${{ env.docker_options }} ${{ env.build_image }} /bin/bash \
+      #       -c 'source /cvmfs/cms.cern.ch/cmsset_default.sh && echo Succeeded to source || exit_on_error "Failed to source"!; \
+      #        scramv1 project CMSSW ${{ env.cmssw_ver }}; cd ${{ env.cmssw_ver }}/src ;  '
+      #   # Can't use the alias cmsrel, would need to echo it to .bashrc. Though this is the only place we need that alias.
 
 
       #   run: |
